"""create new column embed_path

Revision ID: 15f6c0297b55
Revises: 924bc4636f2b
Create Date: 2026-04-23 13:56:17.862882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15f6c0297b55'
down_revision: Union[str, Sequence[str], None] = '924bc4636f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('embed_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'embed_path')
    # ### end Alembic commands ###
