"""add status column, add chunks_path column

Revision ID: 289d32acc296
Revises: 604b701e0a22
Create Date: 2026-04-19 23:14:07.602154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '289d32acc296'
down_revision: Union[str, Sequence[str], None] = '604b701e0a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    filestatus_enum = sa.Enum('UPLOADED', 'PARSED', 'CHUNKED', 'EMBEDDED', 'COMPLETED', name='filestatus')
    filestatus_enum.create(op.get_bind()) 

    op.add_column('files', sa.Column('chunks_path', sa.String(), nullable=True))
    op.add_column('files', sa.Column('status', sa.Enum('UPLOADED', 'PARSED', 'CHUNKED', 'EMBEDDED', 'COMPLETED', name='filestatus'), nullable=False))
    op.alter_column('files', 'parsed_file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'parsed_file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('files', 'status')
    op.drop_column('files', 'chunks_path')
    sa.Enum(name='filestatus').drop(op.get_bind()) 

    # ### end Alembic commands ###
