"""create new column vectors_dim

Revision ID: 648d9689a217
Revises: 15f6c0297b55
Create Date: 2026-04-23 13:58:58.373124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '648d9689a217'
down_revision: Union[str, Sequence[str], None] = '15f6c0297b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('vectors_dim', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'vectors_dim')
    # ### end Alembic commands ###
