"""add new columns

Revision ID: 6a994a3a696e
Revises: 3c6cb9bc53ee
Create Date: 2026-04-15 22:27:54.491161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a994a3a696e'
down_revision: Union[str, Sequence[str], None] = '3c6cb9bc53ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('parsed_file_path', sa.String(), nullable=False))
    op.add_column('files', sa.Column('pages', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'pages')
    op.drop_column('files', 'parsed_file_path')
    # ### end Alembic commands ###
