"""add column chunks_total

Revision ID: 924bc4636f2b
Revises: 289d32acc296
Create Date: 2026-04-22 10:52:56.160666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '924bc4636f2b'
down_revision: Union[str, Sequence[str], None] = '289d32acc296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('chunks_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'chunks_number')
    # ### end Alembic commands ###
